name: module_core
description: A new Flutter module project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  module_external_dependencies:
    path: '../module_external_dependencies'

  cupertino_icons: ^1.0.2

dev_dependencies:
  build_runner: ^2.3.3
  objectbox_generator: ^1.7.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.example.module_core
    iosBundleIdentifier: com.example.moduleCore
