name: module_assets
description: A new Flutter module project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter/Inter-Thin.ttf
          weight: 100
        - asset: fonts/Inter/Inter-ExtraLight.ttf
          weight: 200
        - asset: fonts/Inter/Inter-Light.ttf
          weight: 300
        - asset: fonts/Inter/Inter-Regular.ttf
          weight: 400
        - asset: fonts/Inter/Inter-Medium.ttf
          weight: 500
        - asset: fonts/Inter/Inter-SemiBold.ttf
          weight: 600
        - asset: fonts/Inter/Inter-Bold.ttf
          weight: 700
        - asset: fonts/Inter/Inter-ExtraBold.ttf
          weight: 800
        - asset: fonts/Inter/Inter-Black.ttf
          weight: 900

    - family: Aeonik
      fonts:
        - asset: fonts/Aeonik/Aeonik-Thin.otf
          weight: 100
        - asset: fonts/Aeonik/Aeonik-Thin.otf
          weight: 200
        - asset: fonts/Aeonik/Aeonik-Thin.otf
          weight: 300
        - asset: fonts/Aeonik/Aeonik-Regular.otf
          weight: 400
        - asset: fonts/Aeonik/Aeonik-Medium.otf
          weight: 500
        - asset: fonts/Aeonik/Aeonik-Bold.otf
          weight: 600
        - asset: fonts/Aeonik/Aeonik-Bold.otf
          weight: 700

  assets:
    - animations/
    - vectors/
